### ISSUE TITLE
Need Help Installing Plugin

### ISSUE THREAD

**Issue by jacobhjkim** [ms32035/airflow-dag-dependencies#2]
Hi, I tried to install your awesome plugin on my machine but it doesn't seem to be working.

This is the structure of my `AIRFLOW_HOME`
airflow
+-- dags
+-- plugins
    +---- `__init__.py`
    +---- `dag_dependencies.html`
    +---- `dag_dependencies_plugin.py`

I use docker-compose to run my local airflow, so I modified my `docker-compose.yml` to something like this.
```yaml
    webserver:
        image: my-airflow-image:latest
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=${FERNET_KEY}
            - EXECUTOR=Celery
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - DAG_VOLUME=n
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=5432
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=airflow
            - AIRFLOW__WEBSERVER__NAVBAR_COLOR=#34495e
        volumes:
            - airflow-dag:/usr/local/airflow/dags
            - airflow-plugin:/usr/local/airflow/plugin
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
        ports:
            - "8080:8080"
        command: webserver

    airflow-plugin:
        name: airflow-plugin
        driver: local
        driver_opts:
          device: my-airflow-location/plugin
          o: bind
          type: ext4
```

Airflow version: v1.10.6 (Probably using RBAC UI)

When I run airflow via docker-compose, dag-dependency menu doesn't show up under Brose. Any help would be appreciated.

Thanks
